# Generated by Django 2.1.7 on 2019-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(max_length=1000, upload_to=''),
        ),
    ]
